export const HaveToPay= {

    rentMortgage:"Rent/Mortgage",
    secondMortgage:"Second Mortgage",
    realEstateTaxes:"Real Estate Taxes",
    groceries:"Groceries",
    household:"Household Items",
    cellPhones:"Cell Phones",
    laundry:"Laundry/Dry Cleaning",
    repairMaintenance:"Repair/Maintenance",
    aptHomeInsurance:"Apt/Home Insurance",
    electricity:"Electricity",
    gasHeatingOil:"Gas/Heating Oil",
    water:"Water",
    cableSubscriptions:"Cable/Subscriptions",
    internet:"Internet",
    homePhone:"Home Phone",
    trash:"Trash",
    CarPayment1:"Car Payment 1",
    carPayment2:"Car Payment 2",
    gas:"Gas",
    parking:"Parking",
    tollCharges:"Toll Charges",
    repairMaintenanceAuto:"Repair & Maintenance",
    autoInsurance:"Auto Insurance",
    titleRegistration:"Title/Registration",
    ticketsViolations:"Tickets & Violations",
    metrocardBusPass:"Metrocard/Bus Pass",
    breakfast:"Breakfast",
    lunch:"Lunch",
    medicalCoPayments:"Medical payments",
    healthInsurance:"Health Insurance",
    lifeInsurance:"Life Insurance",
    alimony:"Alimony",
    xhildSupport:"Child Support",
    childCare:"Child Care",
    babySitter:"Baby Sitter",
    schoolTuition:"School Tuition",
    schoolSupplies:"School Supplies",
    accountingFees:"Accounting Fees",
    legalFees:"Legal Fees",
    consultingFees:"Consulting Fees",
    incomeTaxesDue:"Income Taxes Due",
    creditCard1:"Credit Card 1",
    creditCard2:"Credit Card 2",
    studentLoan1:"Student Loan 1",
    studentLoan2:"Student Loan 2",
    miscLoan:"Misc Loan",
}